"""
Diff Noctalia's runtime settings overrides (settings.toml, written by
the GUI settings menu) against the declarative baseline (config.toml,
generated by home-manager from home-manager/noctalia.nix), and print
each difference as a ready-to-paste Nix snippet.

Paths mirror Noctalia's own resolution order (NOCTALIA_*_HOME >
XDG_*_HOME > $HOME/...), see src/util/file_utils.h in the
noctalia-shell source.
"""

import argparse
import os
import sys
from pathlib import Path

try:
    import tomlkit
except ImportError:
    print("error: the tomlkit python package is required",
          file=sys.stderr)
    sys.exit(1)


def config_dir() -> Path:
    for var in ("NOCTALIA_CONFIG_HOME", "XDG_CONFIG_HOME"):
        if os.environ.get(var):
            return Path(os.environ[var]) / "noctalia"
    return Path.home() / ".config" / "noctalia"


def state_dir() -> Path:
    for var in ("NOCTALIA_STATE_HOME", "XDG_STATE_HOME"):
        if os.environ.get(var):
            return Path(os.environ[var]) / "noctalia"
    return Path.home() / ".local" / "state" / "noctalia"


def to_plain(value):
    """Recursively unwrap a tomlkit value into plain Python data."""
    unwrap = getattr(value, "unwrap", None)
    if callable(unwrap):
        return unwrap()
    if hasattr(value, "items"):
        return {k: to_plain(v) for k, v in value.items()}
    if hasattr(value, "__iter__") and not isinstance(value, str):
        return [to_plain(v) for v in value]
    return value


def nix_string(s: str) -> str:
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("${", "\\${")
    )
    return f'"{escaped}"'


def nix_repr(value, indent=0) -> str:
    pad = "  " * indent
    inner_pad = "  " * (indent + 1)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return nix_string(value)
    if isinstance(value, list):
        if not value:
            return "[ ]"
        items = " ".join(nix_repr(v, indent) for v in value)
        return f"[ {items} ]"
    if isinstance(value, dict):
        if not value:
            return "{ }"
        lines = [
            f"{inner_pad}{k} = {nix_repr(v, indent + 1)};"
            for k, v in value.items()
        ]
        return "{\n" + "\n".join(lines) + f"\n{pad}}}"
    return repr(value)


def walk_leaves(node, prefix=()):
    """Yield (dotted_path_tuple, value) for every leaf value."""
    if isinstance(node, dict):
        for k, v in node.items():
            yield from walk_leaves(v, prefix + (k,))
    else:
        yield prefix, node


def get_path(node, path):
    cur = node
    for part in path:
        if not isinstance(cur, dict) or part not in cur:
            return None, False
        cur = cur[part]
    return cur, True


def delete_path(doc, path):
    """Delete a dotted path, pruning now-empty parent tables."""
    parents = [doc]
    cur = doc
    for part in path[:-1]:
        cur = cur[part]
        parents.append(cur)
    del cur[path[-1]]
    for i in range(len(parents) - 1, 0, -1):
        parent, child_key = parents[i - 1], path[i - 1]
        if len(parents[i]) == 0:
            del parent[child_key]
        else:
            break


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="only print the diff, never prompt to clear keys",
    )
    args = parser.parse_args()

    config_path = config_dir() / "config.toml"
    settings_path = state_dir() / "settings.toml"

    if not settings_path.exists():
        print(f"no overrides file at {settings_path}")
        print("nothing GUI-changed yet")
        return 0

    baseline_text = ""
    if config_path.exists():
        baseline_text = config_path.read_text()
    baseline = {}
    if baseline_text:
        baseline = to_plain(tomlkit.parse(baseline_text))

    overrides_doc = tomlkit.parse(settings_path.read_text())
    overrides = to_plain(overrides_doc)

    changed, new, redundant = [], [], []
    for path, gui_value in walk_leaves(overrides):
        baseline_value, present = get_path(baseline, path)
        if not present:
            new.append((path, gui_value))
        elif baseline_value != gui_value:
            changed.append((path, baseline_value, gui_value))
        else:
            redundant.append((path, gui_value))

    if not changed and not new and not redundant:
        print(f"{settings_path} has no keys - nothing to report")
        return 0

    to_review = []
    paste_hint = "  paste into settings = { ... }:"

    for path, old, new_value in changed:
        dotted = ".".join(path)
        print(f"\nCHANGED  {dotted}")
        print(f"  nix (current):  {nix_repr(old)}")
        print(f"  gui (current):  {nix_repr(new_value)}")
        print(paste_hint)
        print(f"    {dotted} = {nix_repr(new_value)};")
        to_review.append(path)

    for path, value in new:
        dotted = ".".join(path)
        print(f"\nNEW      {dotted}  (not declared in Nix at all)")
        print(paste_hint)
        print(f"    {dotted} = {nix_repr(value)};")
        to_review.append(path)

    for path, value in redundant:
        dotted = ".".join(path)
        print(f"\nREDUNDANT {dotted}  (already matches Nix)")
        to_review.append(path)

    if args.dry_run or not to_review:
        return 0

    print(f"\n{len(to_review)} key(s) in settings.toml.")
    print(
        "Once you've copied what you need into "
        "home-manager/noctalia.nix, clear the ones you're"
    )
    print("done with so they stop silently overriding future Nix "
          "changes.\n")

    dirty = False
    for path in to_review:
        dotted = ".".join(path)
        prompt = f"remove '{dotted}' from settings.toml now? [y/N] "
        try:
            answer = input(prompt).strip().lower()
        except EOFError:
            print("\nno input available, skipping remaining prompts")
            break
        if answer == "y":
            delete_path(overrides_doc, path)
            dirty = True

    if dirty:
        settings_path.write_text(tomlkit.dumps(overrides_doc))
        print(f"updated {settings_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
